/**
 * The service worker, as source text.
 *
 * Hand-written rather than generated by a plugin: the plugins hook webpack,
 * the build is already at the droplet's memory ceiling, and dev runs
 * Turbopack where they are switched off. `/sw.js` (a route handler) serves
 * this with the build's id stamped in, so every deploy changes the bytes,
 * the browser installs the new worker, and `activate` drops the old build's
 * caches. A worker that never changed would serve stale chunks forever.
 *
 * Phase A is read-only offline:
 *
 * - `/_next/static/*` — cache-first. Content-hashed, so a hit is always right.
 * - `GET /api/campaigns/:id/state`, and navigations to the session screen
 *   and a hero's play page — network-first, falling back to the last
 *   answer this device saw.
 * - Any other page — the network, or a plain "you are offline" page.
 * - Everything else, every non-GET, `/api/auth/*` and the live stream —
 *   untouched. A cached event stream is nonsense; a cached POST is a lie.
 *
 * **Cached answers are role-filtered for whoever fetched them**, so the data
 * cache is keyed by user: `hn-data-<build>-<userId>`. The page tells the
 * worker who is signed in; a different user arriving deletes every other
 * user's cache before anything is served, and signing out deletes them all.
 *
 * Pure: a string builder. Asserted in `service-worker.test.ts`.
 */

/** Paths the worker answers network-first from the user's cache. */
export const OFFLINE_NAVIGATIONS = [
  /^\/campaigns\/[^/]+\/screen$/,
  /^\/characters\/[^/]+\/play$/,
];
export const OFFLINE_DATA = [/^\/api\/campaigns\/[^/]+\/state$/];

/** Set on an answer the worker gave from its cache, not the network. */
export const CACHED_HEADER = 'X-Hero-Nexus-Cached';

/** The page the worker answers with when there is nothing cached at all. */
const OFFLINE_PAGE = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Offline · Hero Nexus</title><style>body{font-family:system-ui,sans-serif;background:#faf6ef;color:#2b241c;display:grid;place-items:center;min-height:100vh;margin:0;padding:16px}@media (prefers-color-scheme:dark){body{background:#16130f;color:#ece3d4}}main{max-width:28rem;text-align:center}h1{font-family:Georgia,serif;font-weight:600}</style></head><body><main><h1>You are offline</h1><p>This page is not kept for offline use. The session screen and your hero's play page are, once you have opened them online on this device.</p></main></body></html>`;

export function serviceWorkerSource(version: string): string {
  const v = JSON.stringify(version);
  const nav = `[${OFFLINE_NAVIGATIONS.map(r => r.toString()).join(',')}]`;
  const data = `[${OFFLINE_DATA.map(r => r.toString()).join(',')}]`;
  return `/* Hero Nexus service worker. Generated by src/@shared/offline/service-worker.ts. */
const VERSION = ${v};
const STATIC = 'hn-static-' + VERSION;
const DATA = 'hn-data-' + VERSION + '-';
const META = 'hn-meta';
const USER_KEY = '/__hn/user';
const NAV = ${nav};
const API = ${data};
const OFFLINE_PAGE = ${JSON.stringify(OFFLINE_PAGE)};

self.addEventListener('install', () => self.skipWaiting());

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key === META || key === STATIC) continue;
      if (key.startsWith('hn-')) {
        // A new build: the old chunks are gone, and a page cached by the
        // old build points at them. Neither is worth keeping.
        if (key.startsWith('hn-static-') || !key.startsWith(DATA)) {
          await caches.delete(key);
        }
      }
    }
    await self.clients.claim();
  })());
});

// caches.open() creates the cache it names, so reads go through has()
// and match() — after sign-out nothing may quietly come back into being.
async function currentUser() {
  if (!(await caches.has(META))) return null;
  const hit = await (await caches.open(META)).match(USER_KEY);
  return hit ? (await hit.text()) || null : null;
}

async function setUser(id) {
  for (const key of await caches.keys()) {
    if (key.startsWith('hn-data-') && (!id || !key.endsWith('-' + id))) {
      await caches.delete(key);
    }
  }
  if (id) await (await caches.open(META)).put(USER_KEY, new Response(id));
  else await caches.delete(META);
}

// When the worker last had to answer from cache because the network failed.
// In memory only: it is about this moment, and a page asks right after load.
let offlineSince = 0;

self.addEventListener('message', event => {
  const msg = event.data || {};
  if (msg.type === 'status' && event.source) {
    event.source.postMessage({ type: 'status', offlineSince });
  }
  if (msg.type === 'user') event.waitUntil(setUser(msg.id || null));
  if (msg.type === 'signout') {
    event.waitUntil((async () => {
      for (const key of await caches.keys()) await caches.delete(key);
    })());
  }
});

function matches(list, path) {
  return list.some(re => re.test(path));
}

async function networkFirst(request, url, isNavigation) {
  const user = await currentUser();
  if (!user) return fetch(request);
  const cache = await caches.open(DATA + user);
  const key = url.origin + url.pathname;
  try {
    const res = await fetch(request);
    // Only a whole, first-hand answer is worth keeping: not a 304 (no
    // body), not a redirect to /login, not an error.
    if (res.status === 200 && !res.redirected) {
      await cache.put(key, res.clone());
    }
    offlineSince = 0;
    return res;
  } catch (err) {
    if (!offlineSince) offlineSince = Date.now();
    const hit = await cache.match(key);
    if (hit) {
      // Marked, so the page can say it is showing the past.
      const headers = new Headers(hit.headers);
      headers.set(${JSON.stringify(CACHED_HEADER)}, '1');
      return new Response(hit.body, { status: hit.status, headers });
    }
    if (isNavigation) {
      return new Response(OFFLINE_PAGE, {
        status: 503,
        headers: { 'Content-Type': 'text/html; charset=utf-8' },
      });
    }
    throw err;
  }
}

async function cacheFirst(request) {
  const hit = (await caches.has(STATIC))
    ? await (await caches.open(STATIC)).match(request)
    : undefined;
  if (hit) return hit;
  const res = await fetch(request);
  // Only while somebody is signed in: offline mode is theirs, and after
  // sign-out this device keeps nothing — not even the chunks.
  if (res.status === 200 && (await currentUser())) {
    await (await caches.open(STATIC)).put(request, res.clone());
  }
  return res;
}

/** Any other page: the network, and a plain word when there is none. */
async function networkOrOfflinePage(request) {
  try {
    return await fetch(request);
  } catch {
    if (!offlineSince) offlineSince = Date.now();
    return new Response(OFFLINE_PAGE, {
      status: 503,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    });
  }
}

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  const path = url.pathname;
  if (path.startsWith('/api/auth') || path.endsWith('/live')) return;

  if (path.startsWith('/_next/static/')) {
    event.respondWith(cacheFirst(request));
    return;
  }
  if (matches(API, path)) {
    event.respondWith(networkFirst(request, url, false));
    return;
  }
  if (request.mode === 'navigate') {
    event.respondWith(
      matches(NAV, path)
        ? networkFirst(request, url, true)
        : networkOrOfflinePage(request)
    );
  }
});
`;
}
